In [2]:
import numpy as np

# Part 1

## Creating matrix using numpy

In [2]:
matrix_1 = np.array([[2, 3], [6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10, 35, 45], [50, 64, 80], [20, 15, 90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

## Creating matrices with random values

In [8]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.28286691 0.03997535 0.09652693]
 [0.12799728 0.2634936  0.49309835]
 [0.72407344 0.14648819 0.21238944]]


## Creating matrix with random integers

In [9]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[81 69 63 44 44]
 [31 10 94 83 52]
 [54 22 64 29 92]
 [33 51  1 39 47]]


## Creating matrix with all values as 1

In [11]:
matrix_3 = np.ones((2, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# All values as 1 integer
matrix_4 = np.ones((2, 3), dtype=int)
print(matrix_4)

[[1 1 1]
 [1 1 1]]


## Creating a null matrix or 0 matrix

In [13]:
matrix_5 = np.zeros((4,4))
print(matrix_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
matrix_6 = np.zeros((7,7), dtype=int)
print(matrix_6)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


## Creating identity matrix

In [15]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity_matrix_2 = np.eye(5,5, dtype=int)
print(identity_matrix_2)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Transpose of a matrix

In [18]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[76 66 85 76  8]
 [21 35 56 84 22]
 [49 59 69 64 34]
 [13 36 13 79 76]]


In [19]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[76 21 49 13]
 [66 35 59 36]
 [85 56 69 13]
 [76 84 64 79]
 [ 8 22 34 76]]


# Part 2

## Matrix addition  
Rule: They must have the same shape.

In [3]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [4]:
print(A)

[[2 3]
 [4 5]]


In [5]:
print(B)

[[6 7]
 [8 9]]


In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 2)

In [10]:
# Adding 2 matrices
sum = A + B
print(sum)

[[ 8 10]
 [12 14]]


In [11]:
# Create 2 matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [12]:
print(matrix_1)

[[3 8 3]
 [2 3 6]
 [4 7 8]]


In [13]:
print(matrix_2)

[[ 0 10  0]
 [10 17 15]
 [ 3 12 18]]


In [14]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[ 3 18  3]
 [12 20 21]
 [ 7 19 26]]


## Matrix subtraction
Rule: They must have the same shape.

In [15]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [16]:
difference = A - B
print(difference)

[[-4 -4]
 [-4 -4]]


In [17]:
# Create 2 matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [18]:
print(matrix_1)

[[3 8 8]
 [8 6 3]
 [2 1 8]]


In [19]:
print(matrix_2)

[[12  4 16]
 [ 0 16  5]
 [ 8  1 14]]


In [20]:
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[ -9   4  -8]
 [  8 -10  -2]
 [ -6   0  -6]]


## Multiply a matrix by a scalar

In [21]:
x = 5
y = np.random.randint(10, size=(4,4))

In [22]:
print(y)

[[4 3 8 9]
 [1 2 7 7]
 [3 2 9 0]
 [4 1 5 1]]


In [24]:
product = np.multiply(x, y)
print(product)

[[20 15 40 45]
 [ 5 10 35 35]
 [15 10 45  0]
 [20  5 25  5]]


## Multiply 2 matrices  
Rule: Number of columns in first matrix should be the same as the number of rows in the second

In [25]:
# Create 2 matrices with random values
matrix_1 = np.random.randint(5, size=(3,3))
matrix_2 = np.random.randint(5, size=(3,4))

In [26]:
print(matrix_1)

[[3 4 3]
 [0 3 1]
 [2 1 3]]


In [27]:
print(matrix_2)

[[2 4 0 3]
 [2 0 3 1]
 [4 4 3 4]]


In [28]:
product = np.dot(matrix_1, matrix_2)
print(product)

[[26 24 21 25]
 [10  4 12  7]
 [18 20 12 19]]


In [29]:
product.shape

(3, 4)

## Element wise matrix multiplication
Rule: Number of columns in first matrix should be the same as the number of rows in the second

In [30]:
# Create 2 matrices with random values
matrix_1 = np.random.randint(5, size=(3,3))
matrix_2 = np.random.randint(5, size=(3,3))

In [31]:
print(matrix_1)

[[1 2 4]
 [3 1 2]
 [2 0 0]]


In [32]:
print(matrix_2)

[[2 3 3]
 [0 3 2]
 [3 0 3]]


In [33]:
product = np.multiply(matrix_1, matrix_2)
print(product)

[[ 2  6 12]
 [ 0  3  4]
 [ 6  0  0]]
