In [1]:
import numpy as np

## Creating matrix using numpy

In [2]:
matrix_1 = np.array([[2, 3], [6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10, 35, 45], [50, 64, 80], [20, 15, 90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

## Creating matrices with random values

In [8]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.28286691 0.03997535 0.09652693]
 [0.12799728 0.2634936  0.49309835]
 [0.72407344 0.14648819 0.21238944]]


## Creating matrix with random integers

In [9]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[81 69 63 44 44]
 [31 10 94 83 52]
 [54 22 64 29 92]
 [33 51  1 39 47]]


## Creating matrix with all values as 1

In [11]:
matrix_3 = np.ones((2, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# All values as 1 integer
matrix_4 = np.ones((2, 3), dtype=int)
print(matrix_4)

[[1 1 1]
 [1 1 1]]


## Creating a null matrix or 0 matrix

In [13]:
matrix_5 = np.zeros((4,4))
print(matrix_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
matrix_6 = np.zeros((7,7), dtype=int)
print(matrix_6)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


## Creating identity matrix

In [15]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity_matrix_2 = np.eye(5,5, dtype=int)
print(identity_matrix_2)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Transpose of a matrix

In [18]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[76 66 85 76  8]
 [21 35 56 84 22]
 [49 59 69 64 34]
 [13 36 13 79 76]]


In [19]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[76 21 49 13]
 [66 35 59 36]
 [85 56 69 13]
 [76 84 64 79]
 [ 8 22 34 76]]
