In [5]:
import numpy as np

List vs NumPy - Time taken

In [6]:
from time import process_time

Time taken by list

In [7]:
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)


0.09375


Time taken by np array

In [9]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


NumPy Arrays

In [13]:
# List 
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [14]:
np_array = np.array([1, 2, 3, 4, 5]) 
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
# 1 dim array
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [16]:
a.shape

(4,)

In [19]:
# 2 dim array
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
b.shape

(2, 4)

In [22]:
c = np.array([(1, 2, 3, 4), (5, 6, 7, 8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in np arrays

In [23]:
# Create np array of 0
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
# Create np array of 1
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# Array of particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [27]:
# Identity matrix
# No necesita la forma, porque la matriz identidad siempre tiene mismo número de filas y columnas
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
# Numpy array with random values (all between 0 and 1)
b = np.random.random((3,4))
print(b)

[[0.18506181 0.51816687 0.45260853 0.29553854]
 [0.15646265 0.92568078 0.53913057 0.94600347]
 [0.55316575 0.09424766 0.86724101 0.81447023]]


In [30]:
# Random integer values array within a specific range
c = np.random.randint(10, 100, (3,5))
# Argumentos: mínimo, máximo, forma de array
print(c)

[[37 11 70 99 44]
 [61 14 54 22 83]
 [54 99 85 13 93]]


In [36]:
# Array of evenly spaced values --> specifying number of values
d = np.linspace(10, 30, 5)
# Argumentos: min, max, cantidad de valores
print(d)

[10. 15. 20. 25. 30.]


In [41]:
# Array of evenly spaced values --> specifying step
e = np.arange(10, 30, 5)
# Argumentos: min, max (no incluido), step
print(e)

[10 15 20 25]


In [44]:
# Convert list to np array
list2 = [10, 20, 30, 40, 50]

np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [46]:
# Analysing np array
c = np.random.randint(10, 90, (5,5))
print(c)

[[36 42 30 74 58]
 [29 15 13 61 86]
 [76 38 16 36 55]
 [74 15 38 59 48]
 [13 41 17 75 49]]


In [47]:
# Array dimension
print(c.shape)

(5, 5)


In [50]:
# Number of dimensions 
# 2 => filas y columnas
print(c.ndim)

2


In [51]:
# Number of elements in array
print(c.size)

25


In [52]:
# Check data type of values
print(c.dtype)

int32


Mathematical operations on np array

In [56]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
print(list1 + list2)
# Concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [57]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(10, 20, (3,3))

In [58]:
print(a)
print(b)

[[5 5 4]
 [5 3 0]
 [7 5 7]]
[[14 16 12]
 [13 12 16]
 [16 16 17]]


In [59]:
print(a + b)

[[19 21 16]
 [18 15 16]
 [23 21 24]]


In [60]:
print(a - b)

[[ -9 -11  -8]
 [ -8  -9 -16]
 [ -9 -11 -10]]


In [61]:
print(a * b)

[[ 70  80  48]
 [ 65  36   0]
 [112  80 119]]


In [62]:
print(a / b)

[[0.35714286 0.3125     0.33333333]
 [0.38461538 0.25       0.        ]
 [0.4375     0.3125     0.41176471]]


In [63]:
print(np.add(a, b))

[[19 21 16]
 [18 15 16]
 [23 21 24]]


In [64]:
print(np.subtract(a, b))

[[ -9 -11  -8]
 [ -8  -9 -16]
 [ -9 -11 -10]]


In [65]:
print(np.multiply(a, b))

[[ 70  80  48]
 [ 65  36   0]
 [112  80 119]]


In [66]:
print(np.divide(a, b))

[[0.35714286 0.3125     0.33333333]
 [0.38461538 0.25       0.        ]
 [0.4375     0.3125     0.41176471]]


In [67]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[7 8 4]
 [6 9 4]]
(2, 3)


In [69]:
# Transpose (rows become columns and columns become rows)
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 6]
 [8 9]
 [4 4]]
(3, 2)


In [71]:
# otra forma de transponer
trans2 = array.T
print(trans2)

[[7 6]
 [8 9]
 [4 4]]


In [73]:
# Reshape
a = np.random.randint(0, 10, (2,3))
print(a)
print(a.shape)

[[9 6 7]
 [6 1 6]]
(2, 3)


In [74]:
b = a.reshape(3,2)
print(b)

[[9 6]
 [7 6]
 [1 6]]


In [75]:
c = a.reshape(3,-1)
print(c)

[[9 6]
 [7 6]
 [1 6]]
